In [1]:
%matplotlib inline

import os

import numpy as np
import pandas as pd
#import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold  
# data directory
DATA_DIR = os.path.join('..', 'data', 'processed')

In [2]:
# load training data
a_train = pd.read_csv('A_hhold_train.csv', index_col='id')
b_train = pd.read_csv('B_hhold_train.csv', index_col='id')
c_train = pd.read_csv('C_hhold_train.csv', index_col='id')

In [183]:
#b=a_train.count()

In [186]:
[b[i] for i in range(len(b)) if b[i]!=8203]

[]

In [3]:
# load test data
a_test = pd.read_csv('A_hhold_test.csv', index_col='id')
b_test = pd.read_csv('B_hhold_test.csv', index_col='id')
c_test = pd.read_csv('C_hhold_test.csv', index_col='id')

In [4]:
print(a_train.shape, b_train.shape, c_train.shape)

(8203, 345) (3255, 442) (6469, 164)


In [197]:
a_test

wBXbHZmp SlDKnCuu KAJOWiiw DsKacCdL rtPrBBPl tMJrvvut jdetlNNF maLAYXwi  \
id                                                                              
418      JhtDR    GUusz    TuovO    ZYabk    uxuSS    PHMVg    NDTCU    sehIp   
41249    JhtDR    alLXR    BIZns    ZYabk    uxuSS    PHMVg    NDTCU    sehIp   
16205    JhtDR    alLXR    BIZns    ZYabk    feupP    PHMVg    NDTCU    sehIp   
97501    JhtDR    alLXR    BIZns    ZYabk    feupP    VYpgU    NDTCU    TcuXF   
67756    JhtDR    GUusz    BIZns    ZYabk    feupP    PHMVg    NDTCU    sehIp   
17938    JhtDR    GUusz    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
19036    JhtDR    GUusz    BIZns    ZYabk    feupP    PHMVg    NDTCU    sehIp   
61587    JhtDR    GUusz    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
57571    JhtDR    GUusz    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
64203    JhtDR    alLXR    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
30762    JhtDR    alLXR    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
41072    JhtDR    alLXR    TuovO    ZYabk    feupP    PHMVg    NDTCU    cLAGr   
46727    JhtDR    alLXR    BIZns    ZYabk    feupP    PHMVg    NDTCU    sehIp   
78263    JhtDR    alLXR    BIZns    ZYabk    feupP    PHMVg    NDTCU    sehIp   
58110    JhtDR    GUusz    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
13124    JhtDR    GUusz    BIZns    ZYabk    feupP    PHMVg    NDTCU    sehIp   
71752    JhtDR    alLXR    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
75036    JhtDR    GUusz    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
68309    JhtDR    GUusz    BIZns    ZYabk    feupP    PHMVg    NDTCU    TcuXF   
5668     JhtDR    GUusz    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
27937    DkQlr    GUusz    BIZns    ZYabk    feupP    VYpgU    NDTCU    sehIp   
60163    JhtDR    GUusz    TuovO    ZYabk    uxuSS    PHMVg    NDTCU    sehIp   
97835    JhtDR    GUusz    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
7186     JhtDR    GUusz    BIZns    ZYabk    feupP    PHMVg    NDTCU    cLAGr   
36143    JhtDR    GUusz    BIZns    ZYabk    feupP    PHMVg    NDTCU    sehIp   
3465     JhtDR    GUusz    BIZns    ZYabk    feupP    PHMVg    NDTCU    sehIp   
29970    JhtDR    GUusz    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
60973    JhtDR    GUusz    BIZns    ZYabk    feupP    PHMVg    NDTCU    sehIp   
31451    DkQlr    GUusz    BIZns    QGgpH    feupP    PHMVg    NDTCU    cLAGr   
82565    JhtDR    GUusz    BIZns    ZYabk    feupP    PHMVg    NDTCU    TcuXF   
...        ...      ...      ...      ...      ...      ...      ...      ...   
33288    JhtDR    GUusz    TuovO    ZYabk    feupP    PHMVg    NDTCU    TcuXF   
15464    JhtDR    GUusz    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
52752    JhtDR    alLXR    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
46882    JhtDR    GUusz    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
42512    JhtDR    GUusz    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
51944    JhtDR    GUusz    BIZns    ZYabk    feupP    PHMVg    PUBDZ    sehIp   
27765    JhtDR    GUusz    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
23294    JhtDR    alLXR    BIZns    ZYabk    feupP    VYpgU    NDTCU    sehIp   
55056    JhtDR    GUusz    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
26194    JhtDR    GUusz    BIZns    ZYabk    feupP    PHMVg    PUBDZ    sehIp   
25895    JhtDR    alLXR    TuovO    ZYabk    feupP    PHMVg    PUBDZ    sehIp   
37063    JhtDR    GUusz    TuovO    ZYabk    uxuSS    PHMVg    PUBDZ    sehIp   
25775    JhtDR    GUusz    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
69543    JhtDR    GUusz    BIZns    ZYabk    uxuSS    PHMVg    NDTCU    cLAGr   
69529    JhtDR    GUusz    TuovO    ZYabk    feupP    PHMVg    NDTCU    sehIp   
94934    JhtDR    GUusz    BIZns    ZYabk    feupP    PHMVg    PUBDZ    sehIp   
82506    JhtDR    GUusz    TuovO    Z

In [13]:
a_train.poor.value_counts()

False    4500
True     3703
Name: poor, dtype: int64

In [18]:
from sklearn.preprocessing import LabelEncoder
la=LabelEncoder()
la.fit(['True','False'])
a_train['poor']=la.transform(a_train['poor'])

In [20]:
print(a_train['poor'].value_counts())

0    4500
1    3703
Name: poor, dtype: int64


In [23]:
labels = a_train['poor']

In [21]:
def standardize(df, numeric_only=True):
    numeric = df.select_dtypes(include=['int64', 'float64'])
    
    # subtracy mean and divide by std
    df[numeric.columns] = (numeric - numeric.mean()) / numeric.std()
    
    return df
    

def pre_process_data(df, enforce_cols=None):
    print("Input shape:\t{}".format(df.shape))
        

    df = standardize(df)
    print("After standardization {}".format(df.shape))
        
    # create dummy variables for categoricals   使用get_dummies进行one-hot编码
    df = pd.get_dummies(df)
    print("After converting categoricals:\t{}".format(df.shape))
    

    # match test set and training set columns
    if enforce_cols is not None:
        to_drop = np.setdiff1d(df.columns, enforce_cols)
        to_add = np.setdiff1d(enforce_cols, df.columns)

        df.drop(to_drop, axis=1, inplace=True)
        df = df.assign(**{c: 0 for c in to_add})
    
    df.fillna(0, inplace=True)
    
    return df


 #used for B 因为b的数据不干净

from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
def split_data(data,fraction=0.2):
    data_y=data['poor']
#     lb=LabelBinarizer()
#     data_y=lb.fit_transform(data_y)
    data_x=data.drop(['poor'],axis=1)
    train_x,valid_x,train_y,valid_y=train_test_split(data_x,data_y,test_size=fraction)
    return train_x,valid_x,train_y,valid_y




def preprocessing(b_train_in,p=0.8):   
    # 1.null value processing
    ################################
    aa=[]
    bb=[]
    cc=[]
    for c in b_train_in.columns:
        if b_train_in[c].count()<10100:
            aa.append(c)
        elif b_train_in[c].count()==b_train_in.shape[0]:
            bb.append(c)
        else:
            cc.append(c)
    b_train_in.drop(aa,axis=1,inplace=True)
    for c in cc:
        b_train_in[c].fillna(b_train_in[c].mean(),inplace=True)


    
    #2. normalization
    #################################
    temp=b_train_in.select_dtypes(['int64','float64'])
    b_train_in[temp.columns]=(temp-temp.mean())/temp.std()
    
    #3. dummy encoder
    #################################
    b_train_in=pd.get_dummies(b_train_in)
    
    
    
    #4. VarianceThreshold
    #################################
    from sklearn.feature_selection import VarianceThreshold
    sel = VarianceThreshold(threshold=(p * (1 - p)))
    train=sel.fit_transform(b_train_in)
    
    
    
    #5. label encoder
    #################################
    from sklearn.preprocessing import LabelEncoder
    le=LabelEncoder()
    le.fit(['True','False'])
    b_train_in['poor']=le.transform(b_train_in['poor'])
    

    
#   6.split into features and values
#   #################################
    train_x,valid_x,train_y,valid_y=split_data(b_train_in)
    
    
    return train_x,valid_x,train_y,valid_y





In [ ]:
preprocessing(a_train.drop('poor', axis=1))

In [195]:
print("Country A")
aX_train = pre_process_data(a_train.drop('poor', axis=1))   #现在859个feature

Country A
Input shape:	(8203, 344)
After standardization (8203, 344)
After converting categoricals:	(8203, 859)


In [196]:
aX_test = pre_process_data(a_test, enforce_cols=aX_train.columns)

Input shape:	(4041, 344)
After standardization (4041, 344)
After converting categoricals:	(4041, 851)


In [24]:
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split

def data_split(data, label, percentage = 0.2):
    train_x,valid_x,train_y,valid_y = train_test_split(data, label, test_size = percentage)
    return train_x,valid_x,train_y,valid_y

In [31]:
train_x_A ,valid_x_A,train_label_A, valid_label_A = data_split(aX_data, labels)
train_label_A = np.reshape(train_label_A,(-1,1))
valid_label_A = np.reshape(valid_label_A,(-1,1))

/Applications/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:57: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  return getattr(obj, method)(*args, **kwds)


In [32]:
train_label_A

array([[0],
       [0],
       [0],
       ..., 
       [0],
       [1],
       [0]])

In [33]:
print(train_x_A.shape, valid_x_A.shape, train_label_A.shape, valid_label_A.shape)

(6562, 859) (1641, 859) (6562, 1) (1641, 1)


In [206]:
import keras
from keras.layers import Dense,Activation,BatchNormalization,Dropout
from keras import regularizers
from keras.optimizers import Adam

In [217]:
model=keras.models.Sequential()

In [218]:
model.add(Dense(200,input_shape=(859,)))   #,kernel_regularizer = regularizers.l2(0.005)
model.add(BatchNormalization())
model.add(Activation(activation='sigmoid'))
model.add(Dropout(0.7))

model.add(Dense(50))
model.add(BatchNormalization())
model.add(Activation(activation='sigmoid'))
model.add(Dropout(0.5))


model.add(Dense(10))
model.add(Dropout(0.2))
model.add(BatchNormalization())
model.add(Activation(activation='relu'))


model.add(Dense(1))
model.add(BatchNormalization())
model.add(Activation(activation='sigmoid'))

model.compile(loss='binary_crossentropy',metrics=['acc'],optimizer=Adam(0.005))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_135 (Dense)            (None, 200)               172000    
_________________________________________________________________
batch_normalization_124 (Bat (None, 200)               800       
_________________________________________________________________
activation_133 (Activation)  (None, 200)               0         
_________________________________________________________________
dropout_79 (Dropout)         (None, 200)               0         
_________________________________________________________________
dense_136 (Dense)            (None, 50)                10050     
_________________________________________________________________
batch_normalization_125 (Bat (None, 50)                200       
_________________________________________________________________
activation_134 (Activation)  (None, 50)                0         
__________

In [219]:
model.fit(batch_size=200,epochs=100,validation_data=(valid_x_A, valid_label_A),x = train_x_A, y = train_label_A)

Train on 6562 samples, validate on 1641 samples
Epoch 1/100
6562/6562 [==============================] - 7s 991us/step - loss: 0.6049 - acc: 0.6736 - val_loss: 0.4527 - val_acc: 0.7989
Epoch 2/100
6562/6562 [==============================] - 1s 110us/step - loss: 0.5055 - acc: 0.7751 - val_loss: 0.4866 - val_acc: 0.7581
Epoch 3/100
6562/6562 [==============================] - 1s 104us/step - loss: 0.4602 - acc: 0.8052 - val_loss: 0.3849 - val_acc: 0.8422
Epoch 4/100
6562/6562 [==============================] - 1s 106us/step - loss: 0.4179 - acc: 0.8342 - val_loss: 0.3818 - val_acc: 0.8306
Epoch 5/100
6562/6562 [==============================] - 1s 113us/step - loss: 0.3891 - acc: 0.8427 - val_loss: 0.3386 - val_acc: 0.8550
Epoch 6/100
6562/6562 [==============================] - 1s 111us/step - loss: 0.3655 - acc: 0.8595 - val_loss: 0.3562 - val_acc: 0.8336
Epoch 7/100
6562/6562 [==============================] - 1s 116us/step - loss: 0.3530 - acc: 0.8545 - val_loss: 0.3324 - val_acc: 

6562/6562 [==============================] - 1s 110us/step - loss: 0.1717 - acc: 0.9361 - val_loss: 0.4002 - val_acc: 0.8544
Epoch 61/100
6562/6562 [==============================] - 1s 117us/step - loss: 0.1630 - acc: 0.9395 - val_loss: 0.4035 - val_acc: 0.8531
Epoch 62/100
6562/6562 [==============================] - 1s 114us/step - loss: 0.1543 - acc: 0.9409 - val_loss: 0.3767 - val_acc: 0.8537
Epoch 63/100
6562/6562 [==============================] - 1s 111us/step - loss: 0.1677 - acc: 0.9361 - val_loss: 0.3914 - val_acc: 0.8464
Epoch 64/100
6562/6562 [==============================] - 1s 110us/step - loss: 0.1623 - acc: 0.9403 - val_loss: 0.3893 - val_acc: 0.8574
Epoch 65/100
6562/6562 [==============================] - 1s 115us/step - loss: 0.1528 - acc: 0.9442 - val_loss: 0.3918 - val_acc: 0.8568
Epoch 66/100
6562/6562 [==============================] - 1s 106us/step - loss: 0.1520 - acc: 0.9429 - val_loss: 0.3927 - val_acc: 0.8568
Epoch 67/100
6562/6562 [=======================

In [229]:
a_preds = model.predict(aX_test)

In [230]:
a_preds.shape[0]

4041

In [231]:
[a_preds[i] for i in range(len(a_preds)) if a_preds[i][0]>0.5]

[array([ 0.76473755], dtype=float32),
 array([ 0.98627961], dtype=float32),
 array([ 0.79240638], dtype=float32),
 array([ 0.85831028], dtype=float32),
 array([ 0.78750062], dtype=float32),
 array([ 0.73362392], dtype=float32),
 array([ 0.6431644], dtype=float32),
 array([ 0.98371118], dtype=float32),
 array([ 0.86861807], dtype=float32),
 array([ 0.94474411], dtype=float32),
 array([ 0.72969371], dtype=float32),
 array([ 0.99581236], dtype=float32),
 array([ 0.7421549], dtype=float32),
 array([ 0.60781437], dtype=float32),
 array([ 0.60801345], dtype=float32),
 array([ 0.99595708], dtype=float32),
 array([ 0.80344379], dtype=float32),
 array([ 0.98723185], dtype=float32),
 array([ 0.56328607], dtype=float32),
 array([ 0.67975104], dtype=float32),
 array([ 0.98264664], dtype=float32),
 array([ 0.61399108], dtype=float32),
 array([ 0.73178136], dtype=float32),
 array([ 0.55019009], dtype=float32),
 array([ 0.98009253], dtype=float32),
 array([ 0.65231431], dtype=float32),
 array([ 0.688

In [212]:
def make_country_sub(preds, test_feat, country):
    # make sure we code the country correctly
    country_codes = ['A', 'B', 'C']
    
    # get just the poor probabilities
    country_sub = pd.DataFrame(data=preds[:, 0],  # proba p=1
                               columns=['poor'], 
                               index=test_feat.index)

    
    # add the country code for joining later
    country_sub["country"] = country
    return country_sub[["country", "poor"]]

In [213]:
a_sub = make_country_sub(a_preds, a_test, 'A')

In [214]:
a_sub

country      poor
id                     
418         A  0.047584
41249       A -0.038549
16205       A  0.102471
97501       A -0.048807
67756       A  0.011110
17938       A  0.068116
19036       A -0.051820
61587       A  0.012576
57571       A -0.014102
64203       A -0.011252
30762       A  0.031231
41072       A -0.029440
46727       A -0.038735
78263       A -0.012171
58110       A -0.036796
13124       A  0.095086
71752       A -0.002636
75036       A -0.015654
68309       A  0.057762
5668        A  0.009385
27937       A -0.041920
60163       A -0.001262
97835       A -0.008952
7186        A -0.032733
36143       A -0.032006
3465        A -0.021623
29970       A  0.076739
60973       A  0.070905
31451       A -0.007381
82565       A -0.032706
...       ...       ...
33288       A  0.005554
15464       A  0.046602
52752       A -0.050086
46882       A -0.038445
42512       A  0.021384
51944       A  0.029545
27765       A -0.034210
23294       A -0.057886
55056       A  0.115364
26194       A  0.008512
25895       A -0.021390
37063       A  0.076489
25775       A  0.009142
69543       A -0.034481
69529       A -0.004047
94934       A -0.053085
82506       A -0.034490
14865       A -0.049732
74440       A -0.013597
73192       A -0.005486
6778        A -0.003817
177         A  0.025648
59498       A  0.020644
73802       A -0.004061
96606       A  0.058479
7289        A -0.019638
10950       A  0.006393
3346        A  0.120702
50755       A -0.046300
43344       A  0.058703

[4041 rows x 2 columns]